name: video_call
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.6

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  firebase_messaging: ^10.0.2
  flutter_voximplant: ^3.0.0
  flutter_callkit_voximplant: ^2.0.2
  flutter_voip_push_notification: ^0.0.3
  flutter_local_notifications: ^6.0.0
  shared_preferences: ^2.0.6
  permission_handler: ^8.1.1
  firebase_core: ^1.3.0
  cupertino_icons: ^1.0.3
  uuid: ^3.0.4
  device_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

